-- Adds club_join_requests table + join_request_status enum (and FKs/indexes).
--
-- This migration was generated by `drizzle-kit generate` after observing that
-- the schema declared `clubJoinRequests` but no migration created it. The
-- generator also detected drift in unrelated columns (matches.status,
-- tournament_players counts, matches.black_player_id) which previous
-- migrations (0003, 0004) already applied with `IF EXISTS`. Those operations
-- are intentionally omitted here so re-running the suite on environments that
-- already applied 0003/0004 does not fail.
CREATE TYPE "public"."join_request_status" AS ENUM('pending', 'accepted', 'rejected');--> statement-breakpoint
CREATE TABLE "club_join_requests" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"club_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"message" text,
	"status" "join_request_status" DEFAULT 'pending' NOT NULL,
	"decided_by_user_id" uuid,
	"decided_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "club_join_requests" ADD CONSTRAINT "club_join_requests_club_id_clubs_id_fk" FOREIGN KEY ("club_id") REFERENCES "public"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "club_join_requests" ADD CONSTRAINT "club_join_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "club_join_requests" ADD CONSTRAINT "club_join_requests_decided_by_user_id_users_id_fk" FOREIGN KEY ("decided_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "club_join_requests_club_user_pending_unique" ON "club_join_requests" USING btree ("club_id","user_id") WHERE status = 'pending';--> statement-breakpoint
CREATE INDEX "club_join_requests_club_id_idx" ON "club_join_requests" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "club_join_requests_user_id_idx" ON "club_join_requests" USING btree ("user_id");
